rvm:
  - 2.2.6
  - 2.3.2
  - 2.4.1

env:
  global:
    - TEST=true
before_install:
  # https://gist.github.com/ngs/0b5785020afca7701feab717c6a7603a
  - curl -L https://git.io/vSUUX | bash
script: "bundle exec rake test"
