rvm:
- 2.2.6
- 2.3.2
- 2.4.1
env:
  global:
  - TEST=true
before_install:
- curl -L "https://dl.bintray.com/ngs/travis/mecab-with-ipa-dic.tar.gz" -o mecab.tgz && sudo tar xvfz mecab.tgz -C /usr && rm -f mecab.tgz
after_succes:
- bundle exec codeclimate-test-reporter
script: bundle exec rake test
deploy:
  provider: rubygems
  api_key:
    secure: PjIBKKWhCcamn3+X/H2bfDn8m0X6nGTEwZw1LpBbWSiXTxJeUlp1uFjwQ82e8yG6Fk3vLlrCZRks3eM3NIzv9V2l1QHQdivLsha/nBkIpnXB4bIRvJG1bhPVmgOSZQCDJjzgUWSlDljzwFjxJ1NOSYQzbPyvOtu+Ks7/p+BJzHI=
  on:
    tags: true
