rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode

# Bug in jRuby w/ Rouge: https://github.com/jruby/jruby/issues/1392
matrix:
  allow_failures:
    - rvm: jruby-19mode
before_install:
   - sudo apt-get -yV install naist-jdic-utf8
   - sudo apt-get -yV install mecab
   - sudo apt-get -yV install mecab-utils
   - sudo apt-get -yV install mecab-naist-jdic
   - sudo apt-get -yV install libmecab-dev
   - sudo apt-get -yV install libmecab-ruby
script: "bundle exec rake test"

env: TEST=true
